### ISSUE TITLE
CM (2-й розділ): Відредагувати існуючу версію MD до тієї, що є в DOC

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/PACFramework#10]
- [x] таблиці
- [x] рисунки (спочатку перенести в media)
- [ ] перевірити коректність текстів

**Comment by pupenasan** [comment]
@AlonaShak візьміться за цей шматок

**Comment by AlonaShak** [comment]
@pupenasan зроблю

**Comment by AlonaShak** [comment]
В своїй гілці відредагувала таблиці, додала рисунки. Залишилось текст ще раз передивитися

**Comment by pupenasan** [comment]
@AlonaShak  Рисунки треба поправити

**Comment by pupenasan** [comment]
поправив рисунки сам
