### ISSUE TITLE
Використання останнього часу циклу замість константи на прирості T_STEP, подієорієнтваність 

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/PACFramework#29]
У теперішній версії каркасу, яку я почав робити у [PLC_FN](https://github.com/pupenasan/PACFramework/blob/master/cm/2_plcfn.md#опис-структури) є змінна `TSK_LTIME`, яка вказує на плинний (останній) час задачі в мілісекундах. Це можна використати в інших CM.
У багатьох структурах і відповідно функціях використовується `T_STEP`, яка росте по бітовому меандру. Якщо першопочатково не вгадати з часом циклу, можна пролетіти, так як бітові меандри сильно прив'язані до часу циклу. Так, наприклад, меандр 100 мс потребує максимум 50 мс часу циклу. Пропоную використати в прирості `TSK_LTIME` і без меандру, принаймні там, де T_STEP вимірюється в 100 мс. 
Що думаєте?
@AlonaShak @romamirkevich @OlehKlym89 @SerUNderw @matsebuladv      

**UPD**
- максимально відійти від циклічності, врахувати можливість виклику за необхідності:
  - замість використання тіків значень годинників реального часу
  - зміна реалізації фільтрів
- врахувати необхідність зменшення обчислювальних ресурсів, наприклад перевіркою чи змінилася змінна

**Comment by OlehKlym89** [comment]
Як варіант. Точність не постраждає. Це той же t_step залишиться, просто зміниться його формула

**Comment by pupenasan** [comment]
Але є одне але. Якщо ми міряємо значення в 100 мс а не в мс, то точність таки страждати буде. Тоді прийдеться T_STEP зберігати завжди в UDINT. 
Є ще варіант, перевіряти останній цикл на перехід через межу. Наприклад >50 мс, >100 мс, >200 мс ... і оператися на мінімальний меандр. Але в динаміки на кожному циклі це зробити нереально. Тому опиратися можна на якесь максимальне значення циклу, яке апріорі буде рости до останньої зупинки, що також не є показником.
Треба ще покумекати.

**Comment by matsebuladv** [comment]
Для задач, де рахується в 100 мс однозначно треба щось міняти. Я часто помічав, що там час трохи плаває. Я вважаю, що такий підхід можна спробувати. Все одно без тестування не обійтися))

**Comment by pupenasan** [comment]
У контексті даної задачі добавив два поля до структури PLCFN, та модифікував програму для:
-  збереження наносекунд для RT
- час роботи в мс (з перекидуванням) для можливості прив'язки до різниці в мс

@romamirkevich врахуй зміни в кодесісі

**Comment by romamirkevich** [comment]
час циклу рахується в мс і зберігається в змінній UINT, і виходить якщо час циклу менше 1 мс то він взагалі не рахується (так в Codesys оскільки система виводить час циклу в мікросекундах)

**Comment by pupenasan** [comment]
> 
> 
> час циклу рахується в мс і зберігається в змінній UINT, і виходить якщо час циклу менше 1 мс то він взагалі не рахується (так в Codesys оскільки система виводить час циклу в мікросекундах)

У нас plcfn - функціональний блок. Можеш запам'ятовувати в середині в мікросекундах і переводити в мс.

**Comment by pupenasan** [comment]
@matsebuladv @romamirkevich для початку проробіть частину яка стосується фільтрації сигналів аперіодичної ланки з використанням різниці часу. Є існуючі ФБ LAG, але він потребує екземпляру. Можна взяти внутрішню математику LAG і реалізувати самостійно. Знаю що в хелпі по UNITY PRO для LAG є написана реалізація.

**Comment by romamirkevich** [comment]
> @matsebuladv @romamirkevich для початку проробіть частину яка стосується фільтрації сигналів аперіодичної ланки з використанням різниці часу. Є існуючі ФБ LAG, але він потребує екземпляру. Можна взяти внутрішню математику LAG і реалізувати самостійно. Знаю що в хелпі по UNITY PRO для LAG є написана реалізація.
@pupenasan 
за основу взяв FB LEAD_LAG Siemens. Для реалізації даної функції в структуру AIVARCFG необхідно додати змінну VAL_PREV для збереження попереднього значення. Програмна реалізація наступна: 

#VALNOFLT := #AIVARCFG.LOENG + (#RVAL - #AIVARCFG.LORAW) * (#AIVARCFG.HIENG - #AIVARCFG.LOENG) / (#AIVARCFG.HIRAW - #AIVARCFG.LORAW);

IF #FRC THEN (*режим форсування - найвищий пріоритет*)
    IF #INBUF THEN
        #AIVARCFG.VAL := "BUF".VARBUF.VAL;
    END_IF;
    #VAL := #AIVARCFG.VAL;
ELSIF #SML THEN (* режим симуляції - значення змінюється ззовні *)
    #VAL := #AIVARCFG.VAL;
ELSE (*обробка*)
    #SaveVal := #AIVARCFG.VAL_PREV;
    
    #VAL := (("SYS".PLC.TSK_LTIME) / (2.0 * #AIVARCFG.KFLT + "SYS".PLC.TSK_LTIME)) *  (#VALNOFLT - #SaveVal) + #SaveVal;
    #AIVARCFG.VAL_PREV  := #VALNOFLT - (2.0 * #AIVARCFG.KFLT - "SYS".PLC.TSK_LTIME) / (2.0 * #AIVARCFG.KFLT + "SYS".PLC.TSK_LTIME) * (#VALNOFLT - #SaveVal);
END_IF;
