### ISSUE TITLE
Зробити локальний клон репозиторію

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/PACFramework#7]
- [x] Рома @romamirkevich 
- [x] Олег @OlehKlym89 
- [x] Володя @SerUNderw 
- [x] Діма @matsebuladv 
- [x] Альона @AlonaShak

**Comment by SerUNderw** [comment]
Зробив і написав комент

**Comment by AlonaShak** [comment]
Клонувала репозиторій

**Comment by OlehKlym89** [comment]
Зробив

**Comment by matsebuladv** [comment]
Cloned

**Comment by pupenasan** [comment]
Задача вирішена
