### ISSUE TITLE
Створити свою гілку в локальному репозиторії

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/PACFramework#8]
Гілки називати під своїм ніком, усі зміни публікувати туди, періодично синхронізувати з основною гілкою (master)  
- [x] Рома @romamirkevich 
- [x] Олег @OlehKlym89 
- [x] Володя @SerUNderw 
- [x] Діма @matsebuladv 
- [x] Альона @AlonaShak

**Comment by AlonaShak** [comment]
Створила свою гілку в локальному репозиторії alona_shyshak

**Comment by matsebuladv** [comment]
done

**Comment by pupenasan** [comment]
гуд
